### ISSUE TITLE
Create nice CSS

### ISSUE THREAD

**Issue by porygonisaduck** [BentonEdmondson/HeyseForms#2]

**Comment by BentonEdmondson** [comment]
Just sent the request

**Comment by BentonEdmondson** [comment]
Received CSS is here: [style-base.txt](https://github.com/BentonEdmondson/HeyseForms/files/8900579/style-base.txt) (changed to `.txt` to get through github filter). Other option is to adapt [mlibrary/design-system](https://github.com/mlibrary/design-system)

**Comment by BentonEdmondson** [comment]
![image](https://user-images.githubusercontent.com/55590329/174077419-bc6e8167-ca03-4ac0-b0b5-a120f85ee7b8.png)
![image](https://user-images.githubusercontent.com/55590329/174077375-15ebc1dd-48fa-4e45-9e97-e3906db02125.png)
